### ISSUE TITLE
Cannot translate the plugin from translate.wordpress.org

### ISSUE THREAD

**Issue by ramiy** [short-pixel-optimizer/enable-media-replace#14]
The plugin is not translatable from https://translate.wordpress.org/projects/wp-plugins/enable-media-replace

This is an easy fix, we need to configure the `load_plugin_textdomain()` function.

Currently the plugin forces the usage of PO/MO files from the `/languages/` folder, it's an old method and a bad practice because updating translation strings requires you to release a new version with updated PO/MO files.

The new method it is switching to translations using https://translate.wordpress.org, the plugins PO/MO files will be stored in `/wp-content/languages/plugins/` and they will be updated whenever a new string is added . It is done using the WordPress auto-update system.

How is it done you ask? WordPress cron checks every 12 hours for new core version, new plugin/theme versions and new translations strings. If translations strings where updated WordPress will downloads them automatically.

I'm the [Hebrew language General Translation Editor](https://make.wordpress.org/polyglots/teams/?locale=he_IL) and I often translate plugin strings and see them in all my sites without updating the plugin itself.

Enable Media Replace should also use this feature. This way the community will translate the plugin for you.

**Comment by short-pixel-optimizer** [comment]
Thanks for the heads up. I agree we should switch to the new translation system. What would happen with the current translation files if we switch?

**Comment by ramiy** [comment]
@short-pixel-optimizer we can import the current translations to https://translate.wordpress.org.

**Comment by pdobrescu** [comment]
hi @ramiy and thanks for reporting this! As this is now fixed for some time, I will close this issue.
