### ISSUE TITLE
do_action in replace_and_search

### ISSUE THREAD

**Issue by alpipego** [short-pixel-optimizer/enable-media-replace#21]
If the action is defined as `replace_and_search`, the action `wp_handle_upload` does not fire, as it's commented out:

https://github.com/short-pixel-optimizer/enable-media-replace/blob/master/upload.php#L299-L302

Is this an oversight or is there a reason to disable it in this action?

**Comment by pdobrescu** [comment]
hi @alpipego and thanks for reporting this issue. As the plugin has several releases since this issue was added, there is a high chance that it's not there anymore. 

I will close this issue for now and if you still face it, please re-open it and give us more details.
