### ISSUE TITLE
Cannot replace non default Wordpress file types, even those allowed to upload

### ISSUE THREAD

**Issue by greg-thrive** [short-pixel-optimizer/enable-media-replace#31]
Someone else posted about this here: https://wordpress.org/support/topic/file-type-does-not-meet-security-guidelines-try-another-3/

Same issue- trying to enable the ability to replace .xlsm files (which upload successfully) but don't work with the Media Replace. I thought this was fixed in the latest version after looking at that other persons post, but perhaps not?

**Comment by short-pixel-optimizer** [comment]
Hi @greg-thrive, it is fixed and can't reproduce the problem on our test environments, maybe something to do with a specific theme? Could you provide a test env. where it happens?

**Comment by greg-thrive** [comment]
I can create a cloned site of where the issue occurs, what's the best way to get you that info?

**Comment by greg-thrive** [comment]
![Screen Shot 2019-06-12 at 10 16 25 AM](https://user-images.githubusercontent.com/51711619/59358762-252e9300-8cfb-11e9-9d70-5319fa80bc10.png)

**Comment by greg-thrive** [comment]
Wordpress: 5.1.1 
Enable Media Replace Version: 3.3.0

**Comment by greg-thrive** [comment]
Hey I think I figured out my issue- another plugin: Media Library Assistant has it's own upload management section and that seemed to be causing the issue even with the file types needed listed within it. Not totally sure why it was conflicting, but with that part disabled- it's working as expected now.

**Comment by JoseMiralles** [comment]
I'm also experiencing this conflict with Media Library Assistant. Is this something fixable from your end by any chance?

**Comment by short-pixel-optimizer** [comment]
@greg-thrive thanks for sharing your conclusions. Will investigate the conflict with Media Library Assistant.

**Comment by JoseMiralles** [comment]
I don't know if this is the same issue that I'm experiencing, but for some reason I can only replace files if I choose to also replace the filename as well. Otherwise, the file stays the same.

**Comment by short-pixel-optimizer** [comment]
Please contact us on our support channel: https://shortpixel.com/contact mentioning this ticket. Thanks!

**Comment by SeanDKendle** [comment]
I am also receiving this error. Is there a fix?

**Comment by sfeu** [comment]
Same for me with *.bib files

**Comment by bschuiling** [comment]
If WordPress can upload it in the media library, EMR should be able to handle it. 

If the filetype uploads with WP, but the latest test version of EMR ( https://github.com/short-pixel-optimizer/enable-media-replace/tree/updates ) refuses to do this, then please do https://shortpixel.com/contact so we can take a look.

**Comment by pdobrescu** [comment]
@greg-thrive @JoseMiralles @SeanDKendle @sfeu if you still have issues with EMR not handling file types that can be uploaded in the Media Library, please comment on this issue or directly contact support. Thank you for your contribution to get this fixed!
