### ISSUE TITLE
Trailing white space on file ext causes security issue

### ISSUE THREAD

**Issue by montemartin** [short-pixel-optimizer/enable-media-replace#42]
We had a number of files that were triggering a "Replacement file is not the same filetype. This might cause unexpected issues" error. After some deep head scratching I realized all the images causing the issue had a trailing space after the filename extension. It seems like it might be a good idea to trim() file extensions prior to checking them.

If nothing else it would be helpful to add some clarity to the error thrown. "File type does not meet security guidelines." doesn't help debug the issue.

**Comment by short-pixel-optimizer** [comment]
@montemartin thanks a lot for letting us know about this issue. Just pushed a commit fixing this: https://github.com/short-pixel-optimizer/enable-media-replace/commit/426986e4954c82c78edc30d00cbaa9ad00d5d08b
Be grateful if you could give it a try on your case, to check if it fixes.
