### ISSUE TITLE
`EnableMediaReplace\Replacer#replaceWith` will fail when the file is not uploaded file

### ISSUE THREAD

**Issue by yaquawa** [short-pixel-optimizer/enable-media-replace#44]
Hi, thanks for the great plugin!!!

I found it's really useful and I'm using it as a utility library 😀

I found that when calling the `EnableMediaReplace\Replacer#replaceWith` method:

https://github.com/short-pixel-optimizer/enable-media-replace/blob/master/classes/replacer.php#L95

will fail if the`$file` is not a uploaded file(means `is_uploaded_file($file)` returns `false`).
Can we just use the `rename()` instead of the `move_uploaded_file()` here?

**Comment by pdobrescu** [comment]
Hello. The plugin is meant to only work with uploaded files and this is why we're using that function (besides security concerns). Therefore this issue will not be fixed, I'm sorry about that.
