### ISSUE TITLE
Two replace media section on Attachment edit screen

### ISSUE THREAD

**Issue by garretthyder** [short-pixel-optimizer/enable-media-replace#45]
Hello,

When you're on the full Media editor you find both a Replace Media and a Replace Image option;
<img width="1392" alt="Screen Shot 2019-10-29 at 1 50 33 PM" src="https://user-images.githubusercontent.com/8726005/67808876-cc1a8e00-fa54-11e9-8a65-5dfe286b2d3f.png">

The full Media editor is in this format of URL;
https://website.com/wp-admin/post.php?post=XXXX&action=edit

Only one of these is really needed.

Thanks

**Comment by pdobrescu** [comment]
Hello @garretthyder and thanks for reporting this issue. It should already be fixed starting with version 3.3.8, can you please check with the latest plugin version and let us know if you still see 2 `Replace media` sections now?

**Comment by garretthyder** [comment]
Thanks @pdobrescu looks to be fixed for me.
<img width="1349" alt="Screen Shot 2020-03-13 at 8 28 54 AM" src="https://user-images.githubusercontent.com/8726005/76635483-c6ee4500-6504-11ea-891f-3408d0fc77d0.png">
