### ISSUE TITLE
[USABILITY] I can't upload media faster because upload button is on the other page - i made a fix for you

### ISSUE THREAD

**Issue by lucianahanan** [short-pixel-optimizer/enable-media-replace#69]
![image](https://user-images.githubusercontent.com/1200923/100653986-f0b3fa00-3327-11eb-8104-4f900cdbc362.png)

This CSS fixes the page display - the images had bad aspect ratio, were too big, and all the content was pushing the upload button too down, that I always had to scroll page to see the upload button!! Then I made this css fix for you! I hope you take it!

`.wrap.emr_upload_form #message { float: left; margin: 20px; }

.emr_upload_form h1 { line-height:1 !important; }

.emr_upload_form .replace_type.wrapper  { flex:auto!important; width:80%!important}
.emr_upload_form .options.wrapper { flex:auto!important; width:20%!important}

.emr_upload_form .image_chooser.wrapper .emr_drop_area { float: left; }

.emr_upload_form .image_chooser.wrapper .image_placeholder.is_image { width: auto!important; height:400px!important; }
.emr_upload_form .image_chooser.wrapper .image_previews .image_placeholder.is_image img { width: auto!important; height:400px!important; }

.emr_upload_form .image_chooser.wrapper .image_previews { margin:0 !important; }

.emr_upload_form .image_chooser.wrapper .image_previews .image_placeholder { height: 400px !important;}

.upsell-wrapper { display:none}`

**Comment by pdobrescu** [comment]
that page has evolved a bit since your suggestion. thanks, I'll go ahead and close this issue now :-)

**Comment by tammyup** [comment]
Well, that page is still as bad as before - I still need to scroll down to see the upload button, my display monitor only have 1080p height ><
