### ISSUE TITLE
Attempt to read property "post_author" on null

### ISSUE THREAD

**Issue by mehha** [short-pixel-optimizer/enable-media-replace#78]
PHP8, Im using also Tabify Edit Screen plugin which is broken with Enable Media Replace
**Error Attempt to read property "post_author" on null**

  _public function add_meta_boxes($post_type, $post)
  {
      if (! $this->checkImagePermission($post->post_author, $post->ID))
      {  return;  }
 
      add_meta_box('emr-replace-box', __('Replace Media', 'enable-media-replace'), array($this, 'replace_meta_box'), 'attachment', 'side', 'low');
 
      if (isset($_GET['emr_replaced']) && intval($_GET['emr_replaced'] == 1))_

**Comment by pdobrescu** [comment]
Hello @mehha and thanks for opening this issue. Well, this isn't really an error we should fix, but rather the other plugin. However, we added a check for this which should avoid that error, in https://github.com/short-pixel-optimizer/enable-media-replace/commit/43c84d105b182a6ea58d55977f54fd9d3ab65bef.

Can you please fetch the current version of the plugin from the updates branch and confirm back that the error is gone? 

Thanks

**Comment by mehha** [comment]
Thanks @pdobrescu 
Yes, error is gone.
