### ISSUE TITLE
Correct image preview not working despite replacement succeeds ?

### ISSUE THREAD

**Issue by cguidotti** [short-pixel-optimizer/enable-media-replace#81]
I don't know if this is a WordPress problem or if it's related only to the plugin. The fact is that, most of the times, the preview still shows the old version of the image, despite the replacement being successful.
My version of WordPress is 5.9.
The page where I usually get the problem is the "edit media" page, that is `https://[website-domain]/wp-admin/post.php?post=[media-id]&action=edit]`.

**Comment by pdobrescu** [comment]
Hello @cguidotti and thanks for opening this issue.

Can you please give us more details about the caching solutions that you have active on your site? I suspect this has something to do either with a CDN that you might have active, or maybe another caching layer that could lead to such behavior. Our testing with WP 5.9 didn't reveal this type of behavior.

You can give it a try on a simple WordPress setup, which has no caching. This link will create a vanilla WordPress install where you can test this behavior for a few days:

https://demo.tastewp.com/enable-media-replace

Let us know how it goes, please!

**Comment by cguidotti** [comment]
Hello
Thanks for the quick reply!
Maybe I figured it out. It might be related to Chrome's caching system or to Wordpress' Jetpack plugin (although there isn't any performance option activated). For some reason, I had to clear Chrome's cache instead of just forcing page refresh. Clearing all resolved the problem. Sorry if at first I thought it was MediaReplace's fault but the fact Wordpress tells me "it has not been tested with your Wordpress release yet" tricked me.

**Comment by pdobrescu** [comment]
Thanks for the confirmation @cguidotti! I'll go ahead and close this issue, in this case. And thanks for telling me about the 5.9 compatibility, it looks like I haven't committed the updated WP version everywhere, the plugin should now appear as tested with WP 5.9 ;-)
